jenkins file corr

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -2,8 +2,8 @@ pipeline {
     agent any
 
     environment {
-        ARTIFACTORY_URL = 'http://172.31.20.183:8081/artifactory/calc-app-repo'
-        SONARQUBE_URL = 'http://172.31.18.183:9000'
+        ARTIFACTORY_URL = "${ARTIFACTORY_URL}"
+        SONARQUBE_URL = "${SONARQUBE_URL}"
         PATH = "/home/ubuntu/bin:/usr/bin:$PATH"
     }
 
@@ -28,7 +28,7 @@ pipeline {
                     echo "🔍 Running SonarQube Analysis..."
                     withCredentials([string(credentialsId: 'sonarqube-token', variable: 'SONARQUBE_TOKEN')]) {
                         sh '''
-                            mvn sonar:sonar -Dsonar.projectKey=calculator-sonar-project \
+                            mvn sonar:sonar -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                             -Dsonar.host.url=${SONARQUBE_URL} \
                             -Dsonar.login=${SONARQUBE_TOKEN}
                         '''
@@ -54,22 +54,21 @@ pipeline {
                     echo "🚀 Pushing artifact to Artifactory..."
 
                     withCredentials([usernamePassword(credentialsId: 'artifactory-credentials', usernameVariable: 'ARTIFACTORY_USER', passwordVariable: 'ARTIFACTORY_PASSWORD')]) {
-                    sh """
-                    curl -u ${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD} \
-                    -T target/calculator-javaProject-1.0-SNAPSHOT.jar \
-                    "http://107.21.188.29:8081/artifactory/calc-app-repo/com/example/calculator-javaProject/1.0-SNAPSHOT/calculator-javaProject-1.0-SNAPSHOT.jar"
-                    if [ $? -ne 0 ]; then
-                        echo "❌ Failed to upload artifact to Artifactory"
-                        exit 1
-                    fi
-                """
-                
-            }
+                        sh """
+                        curl -u ${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD} \
+                        -T target/${ARTIFACTORY_FILE_NAME} \
+                        "${ARTIFACTORY_URL}/${ARTIFACTORY_PATH}/${ARTIFACTORY_FILE_NAME}"
+                        if [ $? -ne 0 ]; then
+                            echo "❌ Failed to upload artifact to Artifactory"
+                            exit 1
+                        fi
+                        """
+                    }
 
-            echo "✅ Artifact pushed to Artifactory!"
+                    echo "✅ Artifact pushed to Artifactory!"
+                }
+            }
         }
-    }
-}
     }
 
     post {
@@ -91,12 +90,11 @@ pipeline {
                 emailext(
                     subject: subject,
                     body: body,
-                    to: 'amitor2002@gmail.com',
-                    from: 'amitor2002@gmail.com',  
+                    to: '${NOTIFY_EMAIL}',
+                    from: '${FROM_EMAIL}',  
                 )
                 echo "📧 Notification sent!"
             }
         }
     }
 }
-
